CLIENT_COMMAND_PING = "CLIENT_COMMAND_PING"
CLIENT_COMMAND_FIND_OPPONENT="CLIENT_COMMAND_FIND_OPPONENT" # Try to find an opponent in the clients to begin the game
CLIENT_COMMAND_ATTACK_TURN="CLIENT_COMMAND_ATTACK_TURN"

SERVER_COMMAND_PING = "SERVER_COMMAND_PING"
SERVER_COMMAND_FOUND_OPPONENT = "SERVER_COMMAND_FOUND_OPPONENT"
SERVER_COMMAND_NOT_MATCHED = "SERVER_COMMAND_NOT_MATCHED"
SERVER_COMMAND_ATTACK_BLOCK="SERVER_COMMAND_ATTACK_BLOCK"
SERVER_COMMAND_OPPONENT_IS_ATTACKED_BLOCK = "SERVER_COMMAND_OPPONENT_IS_ATTACKED_BLOCK"