CLIENT_COMMAND_PING = "CLIENT_COMMAND_PING"
CLIENT_COMMAND_FIND_OPPONENT="CLIENT_COMMAND_FIND_OPPONENT" # Try to find an opponent in the clients to begin the game


SERVER_COMMAND_PING = "SERVER_COMMAND_PING"
SERVER_COMMAND_FOUND_OPPONENT = "SERVER_COMMAND_FOUND_OPPONENT"
SERVER_COMMAND_NOT_MATCHED = "SERVER_COMMAND_NOT_MATCHED"